
export const SET_CURRENTLY_PLAYING_SONG = "SET_CURRENTLY_PLAYING_SONG"

export const SET_VOLUME = "SET_VOLUME"

export const FETCH_PLAYLIST = "FETCH_PLAYLIST"

export const SET_PLAYLIST = "SET_PLAYLIST"

export const PLAYLIST_FETCH_FAILED = "PLAYLIST_FETCH_FAILED"

export const SET_PLAYING_STATE = "SET_PLAYING_STATE"

export const PREVIOUS_TRACK = "PREVIOUS_TRACK"

export const NEXT_TRACK = "NEXT_TRACK"

export const BEGIN_STREAMING = "BEGIN_STREAMING"

export const TRACK_STREAM_FAILED = "TRACK_STREAM_FAILED"

export const SET_AUDIO_CONTEXT = "SET_AUDIO_CONTEXT"

export const SET_AUDIO_CONTEXT_FAILED = "SET_AUDIO_CONTEXT_FAILED"
