
export const SET_CURRENTLY_PLAYING_SONG = "SET_CURRENTLY_PLAYING_SONG"
export const SET_CURRENTLY_PLAYING_SONG_FAILED = "SET_CURRENTLY_PLAYING_SONG_FAILED"

export const SET_VOLUME = "SET_VOLUME"

export const SET_VOLUME_FAILED = "SET_VOLUME_FAILED"

export const FETCH_PLAYLIST = "FETCH_PLAYLIST"

export const SET_PLAYLIST = "SET_PLAYLIST"

export const PLAYLIST_FETCH_FAILED = "PLAYLIST_FETCH_FAILED"

export const SET_PLAYING_STATE = "SET_PLAYING_STATE"

export const SET_PLAYING_STATE_FAILED = "SET_PLAYING_STATE_FAILED"

export const PREVIOUS_TRACK = "PREVIOUS_TRACK"

export const SET_PREVIOUS_TRACK_FAILED = "SET_PREVIOUS_TRACK_FAILED"

export const NEXT_TRACK = "NEXT_TRACK"

export const SET_NEXT_TRACK_FAILED = "SET_NEXT_TRACK_FAILED"

export const BEGIN_STREAMING = "BEGIN_STREAMING"

export const TRACK_STREAM_FAILED = "TRACK_STREAM_FAILED"

export const SET_AUDIO_CONTEXT = "SET_AUDIO_CONTEXT"

export const SET_AUDIO_CONTEXT_FAILED = "SET_AUDIO_CONTEXT_FAILED"

export const STOP_STREAMING = "STOP_STREAMING"

export const UPLOAD_FILE = "UPLOAD_FILE"

export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED"

export const ADD_UPLOADED_TRACK_TO_PLAYLIST = "ADD_UPLOADED_TRACK_TO_PLAYLIST"
